import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, results } = await req.json();

    if (!email || !results) {
      return new Response(
        JSON.stringify({ error: "Email and results are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY is not configured");
    }

    const { recommendations, summary } = results;

    // Build HTML email
    const careerCards = recommendations
      .map(
        (rec: any) => `
      <div style="background:#f8f9fa;border-radius:12px;padding:20px;margin-bottom:16px;border-left:4px solid ${rec.rank === 1 ? '#4f46e5' : '#e5e7eb'}">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
          <h3 style="margin:0;font-size:18px;color:#1a1a2e">#${rec.rank} ${rec.career_title}</h3>
          <span style="font-size:24px;font-weight:bold;color:${rec.fit_score >= 85 ? '#22c55e' : rec.fit_score >= 70 ? '#eab308' : '#6b7280'}">${rec.fit_score}%</span>
        </div>
        <p style="color:#555;font-size:14px;margin:8px 0">${rec.why_fits}</p>
        <p style="color:#555;font-size:14px;margin:8px 0"><strong>What you'll do:</strong> ${rec.role_description}</p>
        <div style="display:flex;gap:24px;margin-top:12px">
          <div>
            <p style="font-weight:600;font-size:13px;color:#333;margin-bottom:4px">✅ Skills You Have</p>
            <ul style="padding-left:16px;margin:0;color:#555;font-size:13px">
              ${rec.skills_you_have.map((s: string) => `<li>${s}</li>`).join("")}
            </ul>
          </div>
          <div>
            <p style="font-weight:600;font-size:13px;color:#333;margin-bottom:4px">📚 Skills to Develop</p>
            <ul style="padding-left:16px;margin:0;color:#555;font-size:13px">
              ${rec.skills_to_develop.map((s: string) => `<li>${s}</li>`).join("")}
            </ul>
          </div>
        </div>
        <div style="margin-top:12px;background:#fff;border-radius:8px;padding:12px">
          <p style="font-weight:600;font-size:13px;color:#333;margin:0 0 6px">💼 Career Outlook</p>
          <p style="color:#555;font-size:13px;margin:2px 0">Entry: ${rec.career_outlook.salary_entry} | Experienced: ${rec.career_outlook.salary_experienced}</p>
          <p style="color:#555;font-size:13px;margin:2px 0">Growth: ${rec.career_outlook.growth_potential} | Jobs: ${rec.career_outlook.job_availability}</p>
        </div>
        <div style="margin-top:12px">
          <p style="font-weight:600;font-size:13px;color:#333;margin-bottom:4px">🚀 Next Steps</p>
          <ol style="padding-left:16px;margin:0;color:#555;font-size:13px">
            ${rec.next_steps.map((s: string) => `<li style="margin-bottom:4px">${s}</li>`).join("")}
          </ol>
        </div>
      </div>`
      )
      .join("");

    const html = `
    <!DOCTYPE html>
    <html>
    <body style="font-family:'Segoe UI',Arial,sans-serif;background:#f0f2f5;padding:32px 16px;margin:0">
      <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
        <div style="background:linear-gradient(135deg,#1a1a2e,#2d1b69);padding:32px;text-align:center">
          <h1 style="color:#fff;margin:0;font-size:28px">🧞‍♂️ PathGenie</h1>
          <p style="color:rgba(255,255,255,0.7);margin:8px 0 0;font-size:16px">Your Career Recommendations Report</p>
        </div>
        <div style="padding:24px">
          <div style="background:linear-gradient(145deg,#f8f9ff,#f0f2ff);border-radius:12px;padding:20px;margin-bottom:24px;border:1px solid #e5e7eb">
            <p style="color:#6b7280;font-size:13px;margin:0">Top Recommendation</p>
            <h2 style="color:#1a1a2e;margin:4px 0;font-size:22px">${summary.top_recommendation}</h2>
            <p style="color:#6b7280;font-size:14px;margin:8px 0 0">Confidence: <strong style="color:${summary.confidence_level === 'High' ? '#22c55e' : '#eab308'}">${summary.confidence_level}</strong> — ${summary.confidence_explanation}</p>
          </div>
          ${careerCards}
          <div style="text-align:center;margin-top:24px;padding:16px;background:#f8f9fa;border-radius:12px">
            <p style="color:#6b7280;font-size:13px;margin:0">Generated by PathGenie — AI-Powered Career Guidance</p>
          </div>
        </div>
      </div>
    </body>
    </html>`;

    // Send email via Resend
    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "PathGenie <onboarding@resend.dev>",
        to: [email],
        subject: `🧞‍♂️ Your PathGenie Career Report — ${summary.top_recommendation}`,
        html,
      }),
    });

    const resendData = await resendRes.json();

    if (!resendRes.ok) {
      console.error("Resend error:", resendData);
      throw new Error(resendData?.message || "Failed to send email");
    }

    return new Response(
      JSON.stringify({ success: true, message: `Report sent to ${email}` }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("send-report-email error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
